apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Torque-basic-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:
        publicKeyName: tf-key-oregon
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 2
    ssh:
        publicKeyName: tf-key-oregon